// Generated by CoffeeScript 1.6.3
define(function(require, exports, module) {
  var ContainerSurface, Easing, Engine, EventHandler, Modifier, RenderController, SequentialLayout, Surface, Timer, Transform, Transitionable, build, eventHandler, mainContext;
  Engine = require("famous/core/Engine");
  Transform = require("famous/core/Transform");
  Modifier = require("famous/core/Modifier");
  Surface = require("famous/core/Surface");
  ContainerSurface = require("famous/surfaces/ContainerSurface");
  Transitionable = require("famous/transitions/Transitionable");
  Easing = require("famous/transitions/Easing");
  Timer = require("famous/utilities/Timer");
  EventHandler = require('famous/core/EventHandler');
  RenderController = require("famous/views/RenderController");
  SequentialLayout = require("famous/views/SequentialLayout");
  Timer = require("famous/utilities/Timer");
  mainContext = Engine.createContext();
  eventHandler = new EventHandler();
  build = function() {
    var container, l, parts, s1, s2, str;
    container = new ContainerSurface({
      size: [800, 60],
      properties: {
        border: "1px solid steelblue",
        "background-color": "white",
        "border-radius": "5px",
        "z-index": "30"
      }
    });
    l = new SequentialLayout({
      direction: 0
    });
    parts = [];
    l.sequenceFrom(parts);
    str = "this size=true";
    s1 = new Surface({
      size: [true, 50],
      content: "<div style='white-space:nowrap;'>" + str + "</div>",
      properties: {
        "font-size": "30px",
        "background-color": "lightsteelblue",
        "whitespace": "nowrap"
      }
    });
    parts.push(s1);
    str = "and this is too!";
    s2 = new Surface({
      size: [true, 50],
      content: "<div style='white-space:nowrap;'>" + str + "</div>",
      properties: {
        "font-size": "30px",
        "background-color": "steelblue",
        "whitespace": "nowrap"
      }
    });
    console.log(s2.getSize());
    console.log(s2.getSize(true));
    parts.push(s2);
    container.add(l);
    return container;
  };
  return mainContext.add(build());
});
